# 1. create a 3x3x3 array with random values

In [3]:
import numpy as np

In [4]:
e=np.random.random((3,3,3))
e

array([[[0.94400286, 0.92774809, 0.82683   ],
        [0.77009046, 0.39617556, 0.41301399],
        [0.59348121, 0.22273961, 0.11507996]],

       [[0.03285221, 0.24561757, 0.53485514],
        [0.78331319, 0.66902607, 0.35294574],
        [0.47077232, 0.47815855, 0.90470158]],

       [[0.70393015, 0.03789579, 0.32689065],
        [0.26467989, 0.50101339, 0.01195   ],
        [0.87488354, 0.67186517, 0.65023912]]])

# 2.create a 5X5 matrix with values 1,2,3,4 just below the diagonal

In [7]:
import numpy as np

In [20]:
a=np.zeros((5,5))
np.fill_diagonal(a[0:],[1,2,3,4])
a

array([[1., 0., 0., 0., 0.],
       [0., 2., 0., 0., 0.],
       [0., 0., 3., 0., 0.],
       [0., 0., 0., 4., 0.],
       [0., 0., 0., 0., 1.]])

# 3. create a 8x8 matrix and fill it with a checkerboard pattern

In [29]:
matrix=np.zeros((8,8),dtype=int)
matrix[1::2, ::2]=1
matrix[::2, 1::2]= 1
matrix

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

# 4.Normalize a 5x5 random matrix

In [33]:
matrix=np.random.random((5,5))
min_value = np.min(matrix)
max_value = np.max(matrix)

normalized_matrix = (matrix - min_value) / (max_value - min_value)

print("Original Matrix:")
print(matrix)

print("\nNormalized Matrix:")
print(normalized_matrix)

Original Matrix:
[[0.82386841 0.63092409 0.71222364 0.51766673 0.59709034]
 [0.85705278 0.79116949 0.39400284 0.30731005 0.97778659]
 [0.70827127 0.25335556 0.40147101 0.98207128 0.19887868]
 [0.6161454  0.62254277 0.91658141 0.64098755 0.06701948]
 [0.94629884 0.33834058 0.86922927 0.4306543  0.17118099]]

Normalized Matrix:
[[0.82711048 0.61625431 0.70510125 0.49248278 0.57927962]
 [0.8633755  0.79137598 0.35733864 0.26259778 0.99531754]
 [0.70078195 0.20363446 0.3655001  1.         0.14410026]
 [0.60010364 0.60709492 0.92843042 0.627252   0.        ]
 [0.96090666 0.29650901 0.87668239 0.3973926  0.11383127]]


# 5.how to find comman values between two arrays

In [34]:
list1 = [1, 2, 3, 4, 5]
list2 = [3, 4, 5, 6, 7]

common_values = [value for value in list1 if value in list2]

print(common_values)

[3, 4, 5]


# 6.How to get the dates of yesterday,today and tomorrow

In [35]:
from datetime import datetime, timedelta

today = datetime.now().date()

yesterday = today - timedelta(days=1)
tomorrow = today + timedelta(days=1)
print("Yesterday:", yesterday)
print("Today:", today)
print("Tomorrow:", tomorrow)


Yesterday: 2023-09-20
Today: 2023-09-21
Tomorrow: 2023-09-22


# 7.consider two random array A and B, check if they are equal

In [36]:
import numpy as np
A = np.random.rand(5)
B = np.random.rand(5)
are_equal = np.array_equal(A, B)

if are_equal:
    print("Arrays A and B are equal.")
else:
    print("Arrays A and B are not equal.")


Arrays A and B are not equal.


# 8.Create random vector of size 10 and replace the maximum value by 0

In [40]:
a=np.random.random((10))
max_index = np.argmax(a)
a[max_index] = 0

print("Original Random Vector:")
print(a)

Original Random Vector:
[0.6439767  0.2447056  0.         0.28341856 0.23977514 0.76096753
 0.2591262  0.78639465 0.33456294 0.63535763]


# 9.How to print all the values of an array?

In [44]:
import numpy as np

my_array = np.array([1, 2, 3, 4, 5])
for element in my_array:
    print(element)


1
2
3
4
5


# 10.Subtract the mean of each row of a matrix

In [45]:
import numpy as np

# Create a sample matrix (2D NumPy array)
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Calculate the mean of each row
row_means = np.mean(matrix, axis=1)

# Subtract the row means from the matrix
centered_matrix = matrix - row_means.reshape(-1, 1)

print("Original Matrix:")
print(matrix)

print("\nCentered Matrix (Mean Subtracted from Each Row):")
print(centered_matrix)


Original Matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Centered Matrix (Mean Subtracted from Each Row):
[[-1.  0.  1.]
 [-1.  0.  1.]
 [-1.  0.  1.]]


# 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)?

In [46]:
import numpy as np
vector = np.array([1, 2, 3, 4, 5, 6])

indices = np.array([1, 3, 1, 4])
result = np.zeros_like(vector)
for idx in indices:
    result[idx] += 1
result_vector = vector + result

print("Original Vector:")
print(vector)

print("\nResult Vector:")
print(result_vector)


Original Vector:
[1 2 3 4 5 6]

Result Vector:
[1 4 3 5 6 6]


# 12.How to get the diagonal of a dot product?

In [47]:
import numpy as np

matrix1 = np.array([[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]])

matrix2 = np.array([[9, 8, 7],
                    [6, 5, 4],
                    [3, 2, 1]])

dot_product = np.dot(matrix1, matrix2)

diagonal = np.diagonal(dot_product)

print("Dot Product Matrix:")
print(dot_product)

print("\nDiagonal of the Dot Product:")
print(diagonal)


Dot Product Matrix:
[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]

Diagonal of the Dot Product:
[30 69 90]


# 13.How to find the most frequent value in an array?

In [48]:
from collections import Counter

# Create an array
my_array = [1, 2, 2, 3, 3, 3, 4, 4, 5, 5, 5, 5]

# Use Counter to count the frequency of each element
element_counts = Counter(my_array)

# Find the most common element
most_common_element = element_counts.most_common(1)[0][0]

# Find the frequency of the most common element
frequency = element_counts[most_common_element]

print("Array:", my_array)
print("Most common element:", most_common_element)
print("Frequency:", frequency)


Array: [1, 2, 2, 3, 3, 3, 4, 4, 5, 5, 5, 5]
Most common element: 5
Frequency: 4


# 14.How to get the n largest values of an arra

In [49]:
import numpy as np
my_array = np.array([4, 2, 9, 7, 5, 1, 8, 3, 6])


n = 3  

largest_values = np.partition(my_array, -n)[-n:]
largest_values_sorted = np.sort(largest_values)

print("Array:", my_array)
print(f"{n} largest values (sorted):", largest_values_sorted)


Array: [4 2 9 7 5 1 8 3 6]
3 largest values (sorted): [7 8 9]


# 15.How to create a record array from a regular array?

In [51]:
import numpy as np

# Create a regular array (a list of tuples in this example)
regular_array = [(1, 'Alice', 25),
                 (2, 'Bob', 30),
                 (3, 'Charlie', 35)]
dtype = [('ID', int), ('Name', 'U10'), ('Age', int)]
record_array = np.array(regular_array, dtype=dtype)
print("Record Array:")
print(record_array)
print("\nFirst element (ID, Name, Age):", record_array[0])
print("Names:", record_array['Name'])
print("\nName of the second person:", record_array[1]['Name'])


Record Array:
[(1, 'Alice', 25) (2, 'Bob', 30) (3, 'Charlie', 35)]

First element (ID, Name, Age): (1, 'Alice', 25)
Names: ['Alice' 'Bob' 'Charlie']

Name of the second person: Bob


# 16.How to swap two rows of an array

In [52]:
import numpy as np
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
row1_index = 1
row2_index = 2
matrix[[row1_index, row2_index]] = matrix[[row2_index, row1_index]]

print("Matrix with Rows Swapped:")
print(matrix)


Matrix with Rows Swapped:
[[1 2 3]
 [7 8 9]
 [4 5 6]]


# 17.write python code to reshape to the next dimension of numpy array

In [ ]:
x=np.array([[23,34,121],[23,22,67],[686,434,123]])
x

In [53]:
import numpy as np
x = np.array([[23, 34, 121], [23, 22, 67], [686, 434, 123]])
reshaped_x = x.reshape(-1, x.shape[-1])

print("Original array:")
print(x)

print("\nReshaped array to the next dimension:")
print(reshaped_x)


Original array:
[[ 23  34 121]
 [ 23  22  67]
 [686 434 123]]

Reshaped array to the next dimension:
[[ 23  34 121]
 [ 23  22  67]
 [686 434 123]]
